runtime: nodejs18
instance_class: F1
entrypoint: node index.js


env_variables:
  CHATBASE_API_KEY: "943716ed-b316-4a04-a9c0-ca510647640c"
  AIRTABLE_API_KEY: "patppPmnIuHfYoiRM"
  CHATBOT_ID: "GLw23CNLr_KSGrkdx3qhv"
  AIRTABLE_BASE_ID: "appEOgvEOwRnq2pIG"
  AIRTABLE_TABLE_NAME: "tblGR3GlnfuWFNKOE"
  PORT: "8080"
